
def sitePackageDir = "env/lib/python3.5/site-packages"
node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/MG.git'
    }

    stage("build") {
        dir("${WORKSPACE}") {
            echo "#########################"
            echo "# BUILDING DEPENDENCIES #"
            echo "#########################"
            sh "python3 -m venv env"
            sh """. env/bin/activate
            python3 -m pip install -r backend/requirements.txt
            chmod -R 755 backend/
            zip -qj9 backend/presupuesto.zip backend/main.py
            chmod 755 backend/presupuesto.zip
            """
        
        }
    }

    stage('Deploy') {
        dir("${WORKSPACE}"){
            echo "####################"
            echo "# UPLOADING TO AWS #"
            echo "####################"  
                withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
                    sh """
                    . env/bin/activate
                    aws s3 sync backend s3://jmpcba-lambda/
                    aws lambda update-function-code --function-name mg_presupuesto --s3-bucket jmpcba-lambda --s3-key presupuesto.zip
                    deactivate
                    """
            }
        }
    }
}
