
def sitePackageDir = "env/lib/python3.5/site-packages"
node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/MG.git'
    }
/*
    stage("build") {
        dir("${WORKSPACE}") {
            echo "#########################"
            echo "# BUILDING DEPENDENCIES #"
            echo "#########################"
            sh "python3 -m venv env"
            sh """. env/bin/activate
            python3 -m pip install -r backend/requirements.txt"""
            
            sh "cp backend/* ${sitePackageDir}"
            dir(sitePackageDir){
                sh """zip -qr9 presupuesto.zip .
                chmod 755 presupuesto.zip
                mv presupuesto.zip ${WORKSPACE}
                """
            }
        }
    }
*/
    stage('Deploy') {
        dir("${WORKSPACE}"){
            echo "####################"
            echo "# UPLOADING TO AWS #"
            echo "####################"  
                withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
                    sh """
                    python3 -m venv env
                    . env/bin/activate
                    python3 -m pip install -r backend/requirements.txt
                    aws s3 sync backend s3://jmpcba-lambda/
                    aws lambda update-function-code --function-name mg_presupuesto --s3-bucket jmpcba-lambda --s3-key main.py
                    deactivate
                    """
            }
        }
    }
}
