node {
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/MG.git'
        def tfHome = tool name: ‘Terraform’
        env.PATH = “${tfHome}:${env.PATH}”
    }

    if (params.PLAN){
        stage('Plan') {
            ansiColor('gnome-terminal') {
                echo "##################"
                echo "# TERRAFORM PLAN #"
                echo "##################"
                
                dir('infra') {
                    withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1'){
                            sh '''
                                set +x
                                terraform version
                                terraform init
                                terraform plan
                                '''
                    }
                }
            }
        }
    }

    if (params.APPLY){
        stage('Apply') {
            ansiColor('gnome-terminal') {
                echo "###################"
                echo "# TERRAFORM APPLY #"
                echo "###################"
                
                dir('infra') {
                    withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1'){
                            sh '''
                                set +x
                                terraform version
                                terraform init
                                terraform apply -auto-approve
                                '''
                    }
                }
            }
        }
    }
}