node {
    def tfHome = tool name: 'TF', type: 'org.jenkinsci.plugins.terraform.TerraformInstallation'
    
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/MG.git'
    }

    if (params.PLAN){
        stage('Plan') {
            ansiColor('gnome-terminal') {
                echo "##################"
                echo "# TERRAFORM PLAN #"
                echo "##################"
                
                dir('infra') {
                    withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1'){
                        sh "${tfHome}/terraform version"
                        sh "${tfHome}/terraform init"
                        sh "${tfHome}/terraform plan"
                    }
                }
            }
        }
    }

    if (params.APPLY){
        stage('Apply') {
            ansiColor('gnome-terminal') {
                echo "###################"
                echo "# TERRAFORM APPLY #"
                echo "###################"
                
                dir('infra') {
                    withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1'){
                        sh "${tfHome}/terraform version"
                        sh "${tfHome}/terraform init"
                        sh "${tfHome}/terraform apply -auto-approve"
                    }
                }
            }
        }
    }
}